// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/mantil.go"
	"github.com/mantil-io/template-excuses/api/excuses"
)

func main() {
	var api = excuses.New()
	mantil.LambdaHandler(api)
}
