// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/template-excuses/api/ping"
	"github.com/mantil-io/mantil.go"
)

func main() {
	var api = ping.New()
	mantil.LambdaHandler(api)
}
